# Generated by Django 6.0.4 on 2026-04-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_userattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('math', 'Mathematics'), ('gk', 'General Knowledge')], default='tech', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=50),
        ),
    ]
